language: ruby
cache:
  - bundler
install:
  - bundle install
  - git clone --depth 1 git@github.com:sensu-plugins/tom_servo.git

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
notifications:
  email:
    recipients:
      - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always

script:
  - bundle exec rake default
  - gem build *.gemspec
  - gem install *.gem
